### ISSUE TITLE
Option to remove shortcut border

### ISSUE THREAD

**Issue by Dirge70** [enfyna/fx-new-tab#4]
**Is your feature request related to a problem? Please describe.**
In the Shortcut settings Shape drop down,
 there are option for the border shape, but no option to turn it off.

![icon_border_none](https://github.com/enfyna/fx-new-tab/assets/104225510/9e8de7bd-a7cd-45db-a657-f91f4cea7e0f)

**Describe the solution you'd like**
Add a "None" option to remove the border.

**Comment by enfyna** [comment]
Ah but shortcuts need to have a shape. I think making this a seperate checkbox option like Borderless(on/off) would be better.

**Comment by enfyna** [comment]
Added in 1.13.1
